#test package

#Install package:
#require(devtools)
#install_github("zinman/SBadapter")

#load library
#library(SBadapter)

#' Run SparkBeyond titanic example.
#' @param configuration Configuration ID as string. 1 - use only J48, 2 - use RRandomForest, 3 - use defaultList
#' @examples
#' # run_SB_examples()
run_SB_examples <- function(configuration='1') {
  print(paste("Running titanic train example - configuration: ",   configuration))
  write(paste("Running titanic train example - configuration: ",   configuration), stderr())

  res = tryCatch({
    model = runTitanicLearn(configuration)
    runTitanicTestEnrich(model)
    runTitanicTestPredict(model)
    return ("Success")
  }, error = function(e) {
    write (e$message, stderr())
    return (e$message)
  })
  return (res)
}

#' Perform learn on SparkBeyond titanic example.
#' @param configuration Configuration ID as string. 1 - use only J48, 2 - use RRandomForest, 3 - use defaultList.
#' @return SBmodel object containing the result of the learning
#' @examples
#' model = runTitanicLearn()
runTitanicLearn <- function(configuration='1') {
  params = list(
    sessionName = "titanic",
    trainingFilePath = getTitanicFilename(train = TRUE),
    target = "survived"
  )
  additional_params = switch (configuration,
    "1" = list(algorithmsWhiteList = list("RRandomForest")),
    "2" = list(algorithmsWhiteList = NA)
  )

  model = do.call(SBlearn,c(params, additional_params))
  return(model)
}

#' Enrich titanic test dataset with SparkBeyond features.
#' @param a model generated by the titanic learn example.
#' @return data.frame containing regular + enriched values.
#' @examples
#' enriched = runTitanicTestEnrich(model)
runTitanicTestEnrich <- function(model, featureCount = 10) {
  print("Enriching titanic test data")
  enrichRes = model$enrich(getTitanicFilename(train=FALSE), paste(getwd(),"titanic_test_enriched.tsv.gz",sep="/"), featureCount=featureCount)
  if (ncol(enrichRes) == 0) stop("Enrichment failed")
  return(enrichRes)
}

#' Perform prediction on titanic test dataset.
#' @param a model generated by the titanic learn example.
#' @return data.frame containing a prediction for each sample in the test set.
#' @examples
#' # predicted = runTitanicTestPredict(model)
runTitanicTestPredict <- function(model) {
  print("Running titanic test example")
  predictRes = model$predict(getTitanicFilename(train=FALSE), paste(getwd(),"titanic_test.tsv.gz",sep="/"))
  if (nrow(predictRes) == 0) stop("Prediction failed")
  return(predictRes)
}

#' Perform feature search only on Titanic train data.
#' @return data.frame containing a prediction for each sample in the test set.
#' @examples
#' # model = runTitanicFeatureSelectionOnly()
runTitanicFeatureSelectionOnly <- function() {
  print("Performing feature search only on Titanic train data")
  model = SBfeatureSearchOnly(sessionName = "titanic",
                        trainingFilePath = getTitanicFilename(train = TRUE),
                        target = "survived"
  )
  return (model)
}

#' Auxiliary function to get Titanic train/test dataset filename.
#' @param Logical indicating whether to return train or test.
#' @return String with the requested dataset filepath.
#' @examples
#' getTitanicFilename()
getTitanicFilename <- function(train = TRUE) {
  titanic_filename = system.file("extdata", if (train) "titanic_train.tsv" else "titanic_test.csv", package = "SBadapter")
  #data = read.table(titanic_filename, header = TRUE, sep="\t") #inspect file content
  #str(data) #inspect file content
  return(titanic_filename)
}



